spring.datasource.type = com.alibaba.druid.pool.DruidDataSource
spring.datasource.initialSize=20
spring.datasource.minIdle=10
spring.datasource.maxActive=100

spring.datasource.url = jdbc:mysql://localhost:3306/chatting_system?serverTimezone=UTC&useSSL=false
spring.datasource.username = root
spring.datasource.password = 1234

#spring.datasource.driver-class-name = com.mysql.jdbc.Driver
